export const strings = {
  appName: "PENTING",
  appFullName: "Portal Edukasi Nutrisi & Tumbuh Kembang Anak",
  /** Short brand + expansion for UI lockups */
  appNameWithFull: "PENTING (Portal Edukasi Nutrisi & Tumbuh Kembang Anak)",
  tagline: "Hitung status tumbuh, dapatkan resep MPASI hari ini.",
  landingHeadline: "Dari timbang Posyandu ke piring MPASI — dalam hitungan detik.",
  landingSupport:
    "Untuk kader dan ibu: masukkan usia, berat, tinggi, dan jenis kelamin. Langsung dapat status pertumbuhan serta saran resep.",
  ctaCalculator: "Hitung Nutrisi",
  ctaRecipes: "Panduan MPASI",
  navCalculator: "Kalkulator",
  navRecipes: "Panduan MPASI",
  calculatorTitle: "Kalkulator Tumbuh & Nutrisi",
  calculatorSubtitle:
    "Isi keempat data di satu layar. Hasil muncul di bawah formulir — tanpa pindah halaman.",
  fieldAge: "Usia (bulan)",
  fieldWeight: "Berat Badan (kg)",
  fieldHeight: "Tinggi/Panjang Badan (cm)",
  fieldSex: "Jenis Kelamin",
  sexMale: "Laki-laki",
  sexFemale: "Perempuan",
  submitCalculate: "Hitung Sekarang",
  resultTitle: "Hasil Pertumbuhan",
  resultTargetsTitle: "Target Nutrisi Harian",
  resultRecipesTitle: "Rekomendasi Resep",
  zScoreDetail: "Detail angka Z-score (untuk kader)",
  wfaLabel: "Berat menurut usia",
  hfaLabel: "Tinggi menurut usia",
  energyLabel: "Energi",
  proteinLabel: "Protein",
  fatLabel: "Lemak",
  mpasiTooYoung:
    "MPASI mulai diperkenalkan sejak usia 6 bulan. Di bawah 6 bulan, fokususkan ASI eksklusif sesuai anjuran.",
  exclusiveBreastfeedingNote: "Belum ada rekomendasi resep MPASI untuk usia ini.",
  recipesTitle: "Panduan Resep MPASI",
  recipesSubtitle: "Pilih kelompok usia untuk melihat resep yang sesuai.",
  allAges: "Semua",
  servingsLabel: "porsi",
  ingredientsTitle: "Bahan",
  instructionsTitle: "Cara Membuat",
  nutritionTitle: "Informasi Nilai Gizi",
  fruitLabel: "Pelengkap Buah",
  backToGuide: "Kembali ke panduan",
  offlineHint: "Bekerja offline setelah dibuka sekali.",
  unitKkal: "kkal",
  unitGram: "g",
  footerCredit: "Program KKN-PPM UGM · untuk ibu dan kader Posyandu",
  footerPartner: "Sarga Dharma · Universitas Gadjah Mada",
} as const;
